### PR TITLE
Add headers and CMakelist to build on Mac OS 10.10

### PR DESCRIPTION
**Pull request by FinalTheory**
Add a CMakelist.txt so could work on this prog with CLion IDE.
Also fix some missing header problems and linking error on Mac OS 10.10.

### CODE REVIEW

**Comment by proditis** [comment]
Thanks a lot for your contribution :+1: . We have no means of testing it so we'll take your word for it :)

**Comment by FinalTheory** [comment]
Thanks, and seems that all Makefiles in current commit are truncated? Could you please check it?

**Comment by proditis** [comment]
I didn't find any truncation, could you point at the file that seems to be having issues?

**Comment by FinalTheory** [comment]
Sorry for the delay of my reply. Actually I've made a mistake since I'm not familiar with BSD, actually things are OK.

**Pull request merged**
